### ISSUE TITLE
Can't connect to Nilan CTS400 after updating to version 0.1.9.1

### ISSUE THREAD

**Issue by kefdk** [superrob/genvexconnect#1]
Hi,

First of all, thank you for a great integration for Home Assistant and Nilan CTS400. It is very much appreciated.

### Issue
This morning I updated from **version 0.1.4** to **version 0.1.9.1** of Genvex Connect.
After the update, the integration can no longer connect to my Nilan CTS400 gateway connected to my Nilan Comfort 250L system. The integration returns an error when trying to initialize the integration in Home Assistant.

**The error message displayed in Home Assistant is:**

> Timed out while trying to get data from xxxxxxx.remote.lscontrol.dk did not correctly load a model for Model no: 1140, device number: 72280 and slavedevice number: 72270

The log file in Home Assistant does not show anything.

### What have I done?

1. I have validated that my Nilan User App still works. It does.
2. I validated that the Genvex Connect integration was working correctly before the update. It did.
3. I have tried deleting the integration to my gateway, reboot Home Assistant and then add the integration again. This didn't solve the issue.
4. I have tried to re-initialize the integration through the Home Assistant front-end. This didn't solve the issue.

**Comment by superrob** [comment]
I believe this is fixed in release 0.1.9.2.

**Comment by kefdk** [comment]
Hi again,

It now seems like it connects to the gateway, however it reports this error message now, and the configuration fails:

> Timed out while trying to get data from 258519394988.remote.lscontrol.dk has loaded model for CTS 400 with received data: {'temp_supply': 30.2, 'temp_outside': 32.3, 'temp_exhaust': 26.8, 'temp_extract': 27.6, 'humidity': 50.7, 'fan_speed_supply': 33.1, 'fan_speed_extract': 35.3, 'bypass_active': 0.0, 'summer_mode': 0.0, 'co2_level': 0.0, 'filter_days_left': 199.0, 'defrost_active': 0.0, 'defrost_timesincelast': 65535.0}

**Comment by superrob** [comment]
Well, found another typo in the code 😶
Should be fixed in 0.1.9.3

**Comment by kefdk** [comment]
Follow up info:

After trying to re-initiate the integration, I get a message that my credentials are expired.
My flow was to remove the old integration to my gateway and then re-add it through the setup flow.

**Comment by kefdk** [comment]
I can confirm that the 0.1.9.3 version works. The integration is running again.

Thank you for your very quick support / assistance!

**Comment by superrob** [comment]
Great :D!
