### ISSUE TITLE
Bug: CO2 sensor unit of measurement is 'None'

### ISSUE THREAD

**Issue by HairingX** [superrob/genvexconnect#10]
HA complains over the co2 sensor which should have a nativ unit of measurement, but is 'None'.

Context:
I am running a CTS 400 over the Nilan gateway.
I have not bought the optional CO2 extra module for my unit.

Text from HA:

> Entity sensor.nilan_co2_sensor (<class 'custom_components.genvex_connect.sensor.GenvexConnectSensorCO2'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('carbon_dioxide') it is using; expected one of ['ppm']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/superrob/genvexconnect/issues

**Comment by superrob** [comment]
I actually had expected home assistant to just use the default measurement type for the device class. Apparently it doesn't do that.
Fixed in dev branch.
