### ISSUE TITLE
Ikke muligt at ændre værdier for blæserhastighed

### ISSUE THREAD

**Issue by Hoekeren** [superrob/genvexconnect#12]
1. Virkeligt fedt arbejde 💪.
2. Det er ikke muligt at ændre værdierne for blæserhastighederne på de forskellige niveauer.
![Screenshot_2024-09-06-15-29-23-71_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/6459bccf-aa16-4630-89f7-05c00f4e1e57)
![Screenshot_2024-09-06-15-33-27-81_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/e2a2418b-630e-4293-b481-8c44be4dff95)
Hvilket hverken med slideren eller som script:

action: number.set_value
metadata: {}
data:
  value: "75"
target:
  entity_id: number.genvex_local_fraluft_level_4

Det kan man ændre med displayet, så tænker også det burde være muligt med din vej ind.🤞

**Comment by Hoekeren** [comment]
Hvis man nu kunne få fat i en bruger konto fra en forhandler/installatør, tror du så det kunne hjælpe? Den installatør jeg brugte kunne i hvertfald ændre værdierne fra sit display.Måske kunne man trykke ham lidt på maven og få lov.Med venlig hilsenChristianFra: Robin Madsen ***@***.***>Sendt: fredag, september 6, 2024 4:56:30 PMTil: superrob/genvexconnect ***@***.***>Cc: Hoekeren ***@***.***>; Author ***@***.***>Emne: Re: [superrob/genvexconnect] Ikke muligt at ændre værdier for blæserhastighed (Issue #12)
Jeg gætter på du har Optima 270? For desværre ligner det at de har låst de værdier fra at blive ændret gennem connect delen. Ved mindre man er deres bruger konto som har flere rettigheder.
No idea hvorfor man valgte at gøre det, for de eksponerer alligevel ikke de dele i deres app?
Har overvejet at helt fjerne de sliders fra Optima 270 for at undgå folk bliver forvirret over det ikke virker.

**Comment by superrob** [comment]
Svært at sige.
Installatør kontoer har helt klart adgang til de værdier. 

At så bruge deres konto er en helt anden sag, da den nuværende version blot bruger ens email som adgang. 
Dvs, hvis dette skal virke så skulle din enhed havde gemt din installatørs email i dens database over brugere med adgang og du så bagefter angiver den mail.

Når du forresten nævner fra sit display, det var vel ikke bare et Optima Touch display de havde sat til? Sådan var det med mit anlæg, der havde min installatør et med og brugte det midlertidigt imens han indregulerede anlæget.

**Comment by Hoekeren** [comment]
Hej Robin.Ja jeg har et Optima 270 og ja det var et Optima touch display installatøren havde med. Men så er der måske slet ikke brugt et installatør login?!Træls troede ellers lige der var en åbning. Med venlig hilsenChristianFra: Robin Madsen ***@***.***>Sendt: fredag, september 6, 2024 5:25:30 PMTil: superrob/genvexconnect ***@***.***>Cc: Hoekeren ***@***.***>; Author ***@***.***>Emne: Re: [superrob/genvexconnect] Ikke muligt at ændre værdier for blæserhastighed (Issue #12)
Svært at sige.
Installatør kontoer har helt klart adgang til de værdier.
At så bruge deres konto er en helt anden sag, da den nuværende version blot bruger ens email som adgang.
Dvs, hvis dette skal virke så skulle din enhed havde gemt din installatørs email i dens database over brugere med adgang og du så bagefter angiver den mail.
Når du forresten nævner fra sit display, det var vel ikke bare et Optima Touch display de havde sat til? Sådan var det med mit anlæg, der havde min installatør et med og brugte det midlertidigt imens han indregulerede anlæget.

**Comment by superrob** [comment]
Nej, på displayet kan man bare ændre det. Desværre så ligner det at de har låst lige netop de værdier på connect delen :/
Hvilket er super øv, men uden at finde en metode at få flere rettigheder på enheden, så er der vist ikke så meget at gøre der.
