### ISSUE TITLE
Exhaust and supply air measurements starts bouncing

### ISSUE THREAD

**Issue by cvjensen** [superrob/genvexconnect#15]
Hi , 

I'm not quite sure this is a problem with the genvexconnect plugin, but I'll try anyway.

I have a Genvex 360 with Optima 270

It runs fine for some time but then the exhaust and supply air measurements starts bouncing up and down as shown in this graph:

![image](https://github.com/user-attachments/assets/9165e633-6c5d-4073-949f-4926ac618def)

If I reboot the ventilation system everything works fine for a while but as the graph show it starts measuring like crazy again.
This of course also affects the efficiency measurement. 

Hope someone can help me why this happens.

**Comment by superrob** [comment]
How wierd. 
The fact that rebooting your ventilation system solves the issue, most likely indicates a problem on your device.
You could when this is happening see if the official app displays the same temperature readings.

**Comment by cvjensen** [comment]
> How wierd. The fact that rebooting your ventilation system solves the issue, most likely indicates a problem on your device. You could when this is happening see if the official app displays the same temperature readings.

Just tried watching HA and the app when it dropped from 17 to 10 . I then held my hand in front of a supply vent and it feld cooooold ... I think its the ventilation system that is failing ...

**Comment by superrob** [comment]
Does it maybe open up the bypass or not close it correctly?

**Comment by cvjensen** [comment]
> Does it maybe open up the bypass or not close it correctly?

I dont know. I'm guessing now we got it cleared that HA is actually showing me the same measurements as the genvex we can close this . The system is brand new so it seems like this is a genvex issue for now.
