### ISSUE TITLE
Config alias is deprecated and will be removed in HA Core 2025.11

### ISSUE THREAD

**Issue by Newborg** [superrob/genvexconnect#16]
Maybe already on the radar, but wanted to log just in case.

I get the following warning in the log: 

`Config was used from genvex_connect, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'genvex_connect' custom integration`

Thanks for the awesome project!

**Comment by superrob** [comment]
Thanks for the notice. Removed the (Unused) import in the latest version.
