### ISSUE TITLE
Possible to get rotation speed from rotating heat exchanger?

### ISSUE THREAD

**Issue by cvjensen** [superrob/genvexconnect#17]
Hi , 

I wondered if it was possible to get the heat exchanger rotation speed from a Genvex ECO 360 R?

I'm guessing the controller knows it but right now I cant see it in genvexconnect?

**Comment by superrob** [comment]
The integration has the RPM of the two fans. What other rotation speeds are there?

**Comment by cvjensen** [comment]
The rotation speed of the heat exchanger drum itself

![image](https://github.com/user-attachments/assets/c701aad9-f966-479d-b87b-293d5d06dec0)

**Comment by superrob** [comment]
Hmm... there is a modbus register for "Rotor speed" - Might be that?`
However one issue is recognizing different models. It is quite easy with Nilan systems, as they carry their model numbers into the app. 
However it seems like that isn't the case with the inbuilt Genvex devices. 
What model information does the integration show for your system in HA?
For mine (Eco 300 XL) it is: 
Hardware: M: 2010, SD: 0, SDM: 13

**Comment by cvjensen** [comment]
Its probably rotor speed yes . 

Mine says:

Optima 270
by Genvex
Hardware: M: 2010, SD: 0, SDM: 13

**Comment by superrob** [comment]
Hmm... that is a bit troublesome.
With Nilan, the gateway reports the device model. Thus allowing for the integration to have certain "quirks" enabled for different models.
However since the Genvex gateway essentially just reports itself, it isn't much help.

So if i add rotor speed to Optima 270, then everyone will see that value. Even those without the rotor heat exchanger. 
This is however currently also an issue with the preheating, as that is also shown to everyone, even those without the preheater.

**Comment by Newborg** [comment]
I would also love to see the rotor speed of the Genvex ECO 360 R. I don't think it creates too much noise to add it to all Optima 270 as there are also other values shown that are not shared by all models (as you mention).

**Comment by cvjensen** [comment]
I'm ready to test whatever you need . Its probably RPM. 
I was just thinking maybe the special non shared values could just be deactivated by default ? Then people could activate it if they need it ?

**Comment by Newborg** [comment]
Regarding RPM, status from my system

![IMG_20241223_143739](https://github.com/user-attachments/assets/16cfe50a-1c43-4a92-8f15-5f64295591de)

**Comment by superrob** [comment]
Ah! Thank you, that is very helpful.

**Comment by superrob** [comment]
Added in newest release. The entity is disabled by default.
It can simply be enabled from the device menu.

**Comment by cvjensen** [comment]
Thanks alot man !
