### ISSUE TITLE
Air9 data/controls missing

### ISSUE THREAD

**Issue by colin-whittaker** [superrob/genvexconnect#18]
Hello, 

I have a nilan compactP + air9 that I am trying to integrate into home assistant using this module. 

The compactP part has been working perfectly, thanks for making this integration, but none of the data for the air9 unit (air to water heat pump) is present in home assistant. I am assuming because of something odd in the nilan interface
![air9-screenshot-redacted2](https://github.com/user-attachments/assets/c33d8a5c-6317-4e8c-85b7-1b85d0002254)

I can grab any debug data that would help with adding support for the air9

**Comment by superrob** [comment]
Hi Colin,

Most of those values i simply haven't added yet, as nobody have requested them until now :)
One thing that would really help me, would be what model information you have in the HA integration.
It is shown when selecting the device and looks like this:

Hardware: M: 2010, SD: 0, SDM: 13

**Comment by colin-whittaker** [comment]
Hardware: M: 1140, SD: 2763306, SDM: 144

**Comment by superrob** [comment]
Thanks! They are now added in the newest release :)!

**Comment by colin-whittaker** [comment]
working perfectly thanks.
The nilan app is terrible for trying to get data from so this integration makes monitoring the system so much better.
