### ISSUE TITLE
Four controls have stopped working

### ISSUE THREAD

**Issue by KingBendico** [superrob/genvexconnect#2]
![image](https://github.com/user-attachments/assets/9aadd15c-b090-4447-a5a5-002852ac0d3c)
![image](https://github.com/user-attachments/assets/10fb3781-3339-448e-82ab-a24a570b5beb)

The above controls have stopped working on CTS 602

**Comment by superrob** [comment]
What is your model information? 
You can see it under "CTS602" with the letter M, SM, SDN

**Comment by KingBendico** [comment]
Hardware: M: 1141, SD: 2763306, SDM: 12

**Comment by superrob** [comment]
Anything in Home Assistant logs?

**Comment by KingBendico** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 1:32:51 PM (21 occurrences)
Last logged: 1:33:09 PM

Error setting up entry 137118251504.remote.lscontrol.dk for climate
Error setting up entry 137118251504.remote.lscontrol.dk for switch
Error setting up entry 137118251504.remote.lscontrol.dk for number
Error setting up entry 137118251504.remote.lscontrol.dk for button
Error setting up entry 137118251504.remote.lscontrol.dk for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 130, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_setup_entry
    raise ValueError(
ValueError: Config entry 137118251504.remote.lscontrol.dk (01J33K59VRGMVPHW16HRJRGSKK) for genvex_connect.sensor has already been setup!

**Comment by superrob** [comment]
Hmm.. looks like the integration did not unload correctly. Try restarting your home assistant :)!

**Comment by KingBendico** [comment]
Just tried it. Didn't work.

**Comment by KingBendico** [comment]
Logger: homeassistant.components.number
Source: helpers/entity_platform.py:364
integration: Number (documentation, issues)
First occurred: 3:31:35 PM (1 occurrences)
Last logged: 3:31:35 PM

Error while setting up genvex_connect platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/genvex_connect/number.py", line 51, in async_setup_entry
    new_entities.append(GenvexConnectNumberSetpointTemperature(genvexNabto, GenvexNabtoSetpointKey.TEMP_SETPOINT))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/genvex_connect/number.py", line 82, in __init__
    self._attr_native_step = genvexNabto.getSetpointStep(valueKey)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/genvexnabto/genvexnabto.py", line 173, in getSetpointStep
    return self._model_adapter.getSetpointStep(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/genvexnabto/genvexnabto_modeladapter.py", line 95, in getSetpointStep
    return self._loadedModel._setpoints[key]['step']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'step'

**Comment by superrob** [comment]
Thanks! That was exactly what i was looking for. Addressed in newest release :)!
