### ISSUE TITLE
Integration not accepting email

### ISSUE THREAD

**Issue by geltzer** [superrob/genvexconnect#4]
Ive tried adding the integration but the setup stalls on entering the email adress. Where it keeps saying that the emailnadress is not valid.
The adress has been double and tripple checked and verified against the genvex app, but it is still not accepted.

What to do?

**Comment by superrob** [comment]
What controller does your ventilation use?
Have you checked that even the case of the email is 100% the same? Email@email.com and email@email.com is not the same.
It is essentially used as your password.

Have you also checked in Home assistant logs for any errors that might have occured? 
It is important to note that when the integration says your email is invalid, then it is your own genvex connect device rejecting the email, not the integration not accepting it.

**Comment by geltzer** [comment]
The controller is an optima 270
Found my tablet automatically added first letter in the email as capital l, which is normally not a problem as email addresses are normally not case sensitive. So maybe it should be mentioned more specifically.
But thx for the hint

**Comment by superrob** [comment]
I have added a quality of life update, such that when the email entered is not all lower case, it is also tried in all lowercase :)!
