### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by tynor88** [superrob/genvexconnect#6]
Hi,
Very eager to try this integration. I just setup a fresh homeassistant install (docker @ RPi5) + HACS. After I try to add the Genvex Connect integration i see:

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

I have a NILAN gateway running on my local network (same subnet & VLAN)
Docker is running with --net=host parameter (no bridge)

**Comment by superrob** [comment]
Could you check your Home assistant logs when trying to load the configuration flow? 
It might have written something more specific as to why the config flow didn't load.

I have tried installing it on my other machine using HACS and it loads just fine.

**Comment by tynor88** [comment]
I got a little further with a reinstall in HACS...! Now it finds something and i get this when trying to add it:

> 
![Capture](https://github.com/user-attachments/assets/775e98f5-2b93-485f-ac14-d0bf7d3b0d3c)

**Comment by tynor88** [comment]
So i tried with the "Manual" radio button and typed in the API and then it found it!

Not sure what happened with the "Automatic Discovery" - perhaps some bug?
Great work, and thanks for the swift reply!

**Comment by superrob** [comment]
Thanks for the nice log output.
I have fixed the problem :)
